FROM golang:1.24.9-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download 

COPY . .

RUN go build -o kv_node node/node.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/kv_node .

EXPOSE 8080

CMD [ "./kv_node" ]